global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'telegram_alerts'

receivers:
- name: 'telegram_alerts'
  telegram_configs:
  - bot_token: 'COLOQUE_AQUI_O_SEU_TOKEN_DO_BOT'
    api_url: 'https://api.telegram.org'
    chat_id: 000000000 # COLOQUE_AQUI_O_SEU_CHAT_ID_DO_UTILIZADOR
    parse_mode: 'HTML'
    message: |
      <b>ðŸ”” ALERTA IOT: {{ .Status | toUpper }}</b>
      {{ range .Alerts }}
      <b>ServiÃ§o:</b> {{ .Labels.alertname }}
      <b>Resumo:</b> {{ .Annotations.summary }}
      <b>DescriÃ§Ã£o:</b> {{ .Annotations.description }}
      <b>Severidade:</b> {{ .Labels.severity | toUpper }}
      <b>Hora:</b> {{ .StartsAt.Format "15:04:05" }}
      {{ end }}
