global:
  scrape_interval: 10s # Recolher m√©tricas a cada 10 segundos
  scrape_timeout: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Exemplo de job para o Backend Laravel (quando estiver configurado)
  # - job_name: 'laravel_backend'
  #   metrics_path: '/metrics'
  #   static_configs:
  #     - targets: ['host.docker.internal:8000']

  # Exemplo de job para os Simuladores (Pushgateway ou servidor HTTP simples)
  # - job_name: 'iot_simulators'
  #   static_configs:
  #     - targets: ['host.docker.internal:8001']
